# Generated by Django 6.0.4 on 2026-05-08 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0002_produto_imagem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoria",
            old_name="nome",
            new_name="Categoria",
        ),
        migrations.RenameField(
            model_name="fabricante",
            old_name="nome",
            new_name="Fabricante",
        ),
        migrations.RenameField(
            model_name="produto",
            old_name="nome",
            new_name="Produto",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="imagem",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="msg_promocao",
        ),
        migrations.AddField(
            model_name="produto",
            name="msgPromocao",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categoria",
                to="loja.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="fabricante",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fabricante",
                to="loja.fabricante",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="promocao",
            field=models.BooleanField(default=True),
        ),
    ]
