# Generated by Django 6.1 on 2026-08-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0005_usuario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoria",
            old_name="Categoria",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="fabricante",
            old_name="Fabricante",
            new_name="nome",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="alterado_em",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="criado_em",
        ),
        migrations.RemoveField(
            model_name="fabricante",
            name="alterado_em",
        ),
        migrations.RemoveField(
            model_name="fabricante",
            name="criado_em",
        ),
        migrations.AddField(
            model_name="fabricante",
            name="site",
            field=models.URLField(blank=True, null=True),
        ),
    ]
